[build]
  command = "python -m pip install -r requirements.txt"
  functions = "project/.netlify/functions"  # Chemin vers les fonctions Netlify

[[plugins]]
  package = "@netlify/plugin-functions-core"
