[build]
  command = "python -m pip install -r requirements.txt && npm install -D @netlify/plugin-functions-core"
  publish = "/opt/build/repo"

[functions]
  directory = "project/.netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-core"